---
apiVersion: v1
kind: Namespace
metadata:
  name: tensorflow-cpu
  labels:
    app: tensorflow-cpu
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow-cpu
  labels:
    app: tensorflow-cpu
  namespace: tensorflow-cpu
spec:
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      app: tensorflow-cpu
  template:
    metadata:
      name: tensorflow-cpu
      labels:
        app: tensorflow-cpu
      namespace: tensorflow-cpu
    spec:
      containers:
        - name: tensorflow-cpu
          image: kyechou/tensorflow:cpu-arch
          command:
            - 'python'
          args:
            - '/benchmarks/scripts/tf-cpu-test.py'
          volumeMounts:
            - mountPath: /benchmarks
              name: benchmarks
      volumes:
        - name: benchmarks
          nfs:
            server: '140.110.16.155'
            path: /benchmarks
            readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Never
