---
apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow
  labels:
    app: tensorflow
  namespace: user
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: tensorflow
      namespace: user
    spec:
      containers:
        - name: tensorflow
          image: kyechou/tensorflow:cpu-arch
          command:
            - 'python'
          args:
            - '/benchmarks/scripts/tf-cpu-test.py'
          volumeMounts:
            - mountPath: /benchmarks
              name: benchmarks
              readOnly: true
      volumes:
        - name: benchmarks
          nfs:
            server: '140.110.16.155'
            path: /nfs/benchmarks
            readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Never
