---
apiVersion: batch/v1
kind: Job
metadata:
  name: tf-ps$PS_IDX
  labels:
    app: tf-ps$PS_IDX
  namespace: user
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: tf-ps$PS_IDX
      namespace: user
    spec:
      containers:
        - name: tf-ps$PS_IDX
          image: kyechou/tensorflow:cpu-arch
#          resources:
#            requests:
#              alpha.kubernetes.io/nvidia-gpu: 1
#            limits:
#              alpha.kubernetes.io/nvidia-gpu: 1
          env:
            - name: PATH
              value: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/nvidia/bin"
            - name: LD_LIBRARY_PATH
              value: "/nvidia/lib"
          command:
            - 'python'
          args:
            - /benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
            - --local_parameter_device=cpu
#            - --local_parameter_device=gpu
#            - --num_gpus=1
            - --batch_size=$BATCH
            - --model=$MODEL
            - --variable_update=$UPDATE
            - --cross_replica_sync
            - --use_nccl=True
            - --job_name=ps
            - --ps_hosts=$PS_HOSTS
            - --worker_hosts=$WORKER_HOSTS
            - --task_index=$PS_IDX
          volumeMounts:
            - mountPath: /benchmarks
              name: benchmarks
              readOnly: true
            - mountPath: /nvidia/bin
              name: nv-bin
              readOnly: true
            - mountPath: /nvidia/lib
              name: nv-lib
              readOnly: true
      volumes:
        - name: benchmarks
          nfs:
            server: '140.110.16.155'
            path: /nfs/benchmarks
            readOnly: true
        - name: nv-bin
          nfs:
            server: '140.110.16.155'
            path: /nvidia/bin
            readOnly: true
        - name: nv-lib
          nfs:
            server: '140.110.16.155'
            path: /nvidia/lib
            readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master:
        #kubernetes.io/hostname: bra23
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps$PS_IDX
  labels:
    app: tf-ps$PS_IDX
  namespace: user
spec:
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  selector:
    app: tf-ps$PS_IDX
