---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tensorboard
  labels:
    app: tensorboard
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      labels:
        app: tensorboard
      namespace: user
    spec:
      containers:
        - name: tensorboard
          image: kyechou/tensorflow:cpu-arch
          command:
            - 'tensorboard'
          args:
            - '--logdir=/log'
          ports:
            - containerPort: 6006
          volumeMounts:
            - mountPath: /log
              name: log
          livenessProbe:
            httpGet:
              path: /
              port: 6006
            initialDelaySeconds: 30
            timeoutSeconds: 30
      volumes:
        - name: log
          nfs:
            server: '140.110.16.155'
            path: /...
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master:
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard
  labels:
    app: tensorboard
  namespace: user
spec:
  ports:
    - protocol: TCP
      targetPort: 6006
      port: 80
  selector:
    app: tensorboard
