---
apiVersion: v1
kind: Namespace
metadata:
  name: user
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: user
  name: user
rules:
  - apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'extensions'
      - 'autoscaling'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user-binding
  namespace: user
subjects:
  - kind: User
    name: user
    apiGroup: ""
roleRef:
  kind: Role
  name: user
  apiGroup: ""
